### ISSUE TITLE
2.0.4 Package Broken?

### ISSUE THREAD

**Issue by pdentener** [amitdahan/ngx-filesize#49]
Just installed the 2.0.4 package, but that wasn't working for me anymore (in the latest Angular 9.0.7). Both `ng build (--prod)` and Visual Studio Code complained:

On line `import { NgxFilesizeModule } from 'ngx-filesize';` with `Cannot find module 'ngx-filesize'.`

It seems the Angular Library / package is broken? Reverting back to 2.0.2 fixed it for me.

**Comment by amitdahan** [comment]
Hey @pdentener! Thank you very much for raising this! I’m on it!

**Comment by amitdahan** [comment]
Sorry guys! Broke publishing flow while switching to yarn.
Fixed! It only took going up to `2.0.9` to fix!

**Comment by pdentener** [comment]
Sorry to report, but it's still not working for me. Just uninstalled `2.0.2`. I restarted Visual Studio Code and made sure the `ngx-filesize` directory was gone in `node_modules`. After that installed `2.0.9`, but I'm still getting the same error. Am I perhaps doing something wrong here?

I'm no Node JS or NPM expert by any means, but isn't your `lib` folder missing? And the reference to it from `package.json` via `files` and perhaps `module`?

**Comment by amitdahan** [comment]
Sorry about that, seems it worked for me a second ago. Seems it's still publishing the root dir instead of `dist/ngx-filesize`. On it again. 😞

**Comment by amitdahan** [comment]
`2.0.12` is out and fixed. Truly sorry about that!

```
➜ ls -la node_modules/ngx-filesize
total 40
drwxr-xr-x   13 amitda  361602828   416B Mar 20 17:31 .
drwxr-xr-x  792 amitda  361602828    25K Mar 20 17:31 ..
-rw-r--r--    1 amitda  361602828   483B Mar 20 17:23 README.md
drwxr-xr-x    6 amitda  361602828   192B Mar 20 17:31 bundles
drwxr-xr-x    5 amitda  361602828   160B Mar 20 17:31 esm2015
drwxr-xr-x    5 amitda  361602828   160B Mar 20 17:31 esm5
drwxr-xr-x    4 amitda  361602828   128B Mar 20 17:31 fesm2015
drwxr-xr-x    4 amitda  361602828   128B Mar 20 17:31 fesm5
drwxr-xr-x    4 amitda  361602828   128B Mar 20 17:31 lib
-rw-r--r--    1 amitda  361602828    78B Mar 20 17:23 ngx-filesize.d.ts
-rw-r--r--    1 amitda  361602828   774B Mar 20 17:23 ngx-filesize.metadata.json
-rw-r--r--    1 amitda  361602828   2.0K Mar 20 17:31 package.json
-rw-r--r--    1 amitda  361602828    80B Mar 20 17:23 public-api.d.ts
➜
```

**Comment by pdentener** [comment]
Just tested 2.0.12 and can confirm it works! 😀

No need to apologise. Thank you for the package.
